import { makeStyles } from '@material-ui/core';
const CustomiseStyles = makeStyles((theme) => ({
	root: {
		backgroundColor: '#f0f5ff',
		height: '100vh',
		position: 'relative',
	},
	topbar: {
		height: '12%',
		backgroundColor: '#F0F5FF',
	},
	logobox: {
		backgroundColor: '#28334B',
		height: '100%',
		position: 'relative',
		display: 'flex',
		justifyContent: 'center',
		alignItems: 'center',
	},
	logo: {
		height: '55px',
	},
	tablink: {
		backgroundColor: '#f2f2f2',
		margin: '10px 0',
		color: '#111',
		width: '75%',
		borderRadius: '5px',
		'&:active': {
			backgroundColor: '#fff',
		},
	},
	botombox: {
		backgroundColor: '#f0f5ff',
		height: '88%',
		position: 'relative',
	},
	typepanel: {
		width: '100%',
		height: 'fit-content',
		display: 'flex',
		flexWrap: 'wrap',
		flexDirection: 'row',
		justifyContent: 'space-around',
		alignItems: 'center',
		overflowY: 'scroll',
		// backgroundColor: '#fff',
	},
	typeimage: {
		// height: '80px',
		width: '80%',
	},
	buttonimage: {
		height: '40px',
	},
	rightpane: {
		width: '100%',
		height: '100%',
		position: 'relative',
		overflowY: 'scroll',
		// backgroundColor: 'purple',
	},
	divider: {
		height: '2px',
		margin: '25px 0',
		backgroundColor: 'grey',
	},
	typepaper: {
		display: 'flex',
		flexDirection: 'column',
		transition: '0.3s',
		alignItems: 'center',
		marginBottom: '10px',
		justifyContent: 'space-between',
		marginTop: '10px',
		marginLeft: '5px',
		transition: '0.3s',
		height: '130px',
		// height: 'fit-content',
		width: '110px',
		// minWidth: '140px',
		// maxWidth: 'fit-content',
		backgroundColor: '#fff',
		padding: '5px ',
		'&:hover': {
			cursor: 'pointer',
		},
	},
	mobtypepaper: {
		display: 'flex',
		flexDirection: 'column',
		transition: '0.3s',
		alignItems: 'center',
		marginBottom: '10px',
		justifyContent: 'space-between',
		marginTop: '5px',
		marginLeft: '5px',
		transition: '0.3s',
		height: '150px',
		width: '140px',
		// minWidth: '130px',
		// maxWidth: '140px',
		backgroundColor: '#fff',
		padding: '5px ',
		'&:hover': {
			cursor: 'pointer',
		},
	},
	buttonpaper: {
		width: '90px',
		// minWidth: '80px',
		// maxWidth: 'fit-content',
		margin: '5px 6px',
		padding: '4px',
		display: 'flex',
		flexDirection: 'column',
		justifyContent: 'space-between',
		alignItems: 'center',
	},
	mobmain: {
		height: '100vh',
		backgroundColor: '#f0f5ff',
	},
	addtocartbutton: {
		backgroundColor: '#387A76',
	},
	aaddtontext: {
		color: 'white',
	},
	mobtabs: {
		height: '100%',
		position: 'relative',
		width: 'fit-content',
		// overflowX: 'scroll',
		display: 'flex',
		alignItems: 'center',
		flexDirection: 'row',
		backgroundColor: 'white',
		borderRadius: '20px 20px 0 0',
	},
	mobtablink: {
		height: '90px',
		width: '120px',
		transition: '0.5s',
		color: 'white',
		backgroundColor: '#f2f2f2',
	},
	bigimagecont: {
		display: 'flex',
		justifyContent: 'center',
		alignItems: 'center',
		height: '65%',
		// backgroundColor: 'red',
	},
	bigimage: {
		width: '50%',
		height: '80%',
		objectFit: 'contain',
		bckgroundColor: '#f2f2f2',
	},
	bigimagedesk: {
		// width: '50%',
		// height: '80%',
		objectFit: 'contain',
		bckgroundColor: '#f2f2f2',
	},
	selectedbox: {
		padding: '20px 0',
		height: 'fit-content',
		backgroundColor: 'red',
	},
	selectedpaper: {
		height: '50px',
		padding: '5px',
		// width: '120px',
		backgroundColor: 'white',
		boxShadow: '0 0 8px -5px rgba(1,1,1,0.3)',
	},
	addcartbutton: {
		color: 'white',
		// padding: '8px 16px',
		height: '44px',
		width: '139px',
		backgroundColor: '#28334B',
		'&:hover': {
			backgroundColor: '#253049',
		},
	},
	productname: {
		fontSize: '24px',
		color: '#282c3f',
		fontWeight: '500',
	},
	adbutontext: {
		fontSize: '15px',
		color: 'black',
		padding: '5px 10px',
		borderRadius: '5px',
		backgroundColor: 'white',
	},
	customappmob: {
		padding: '0 16px',
		height: '8vh',
		backgroundColor: '#28334B',
		display: 'flex',
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
	},
	line: {},
	variation: {
		color: '#303030',
		fontSize: '18px',
	},
}));

export default CustomiseStyles;
